/** Clinical vignette for engine QA (Oliver). */
export const OLIVER_VIGNETTE = `Mum reports that from very early childhood Oliver seemed different to other children socially. She described him as a baby who was "happy left alone for hours" and said he did not naturally seek people out for interaction in the same way his siblings did. She recalled that he rarely pointed things out just to share enjoyment and often appeared more interested in objects than people. Instead of showing toys, he would often line them up or focus on specific parts such as wheels or moving components. She remembers trying to engage him in pretend games but he would usually take over the play in a repetitive or scripted way rather than building shared imaginative play.

Mum stated that response to name was inconsistent throughout toddlerhood despite normal hearing checks. She described needing to physically approach him or touch him to gain his attention. Joint attention appeared reduced. For example, if parents pointed something out in the environment he often looked at their hand rather than following the point naturally. Parents also reported limited use of gestures early on, with Oliver frequently leading adults by the hand toward objects instead of pointing or verbally requesting.

During the assessment Oliver frequently interrupted conversation to return discussion back to transport systems and train routes. He demonstrated extensive factual knowledge regarding train stations, timetables, and public transport mapping. Attempts to redirect conversation were often unsuccessful. Eye contact was intermittent and tended to occur mainly when discussing preferred interests or requesting clarification. Prosody appeared somewhat atypical with speech occasionally sounding overly formal, monotone, and lecture-like for his age.

Parents report significant difficulty with reciprocal interaction. Mum stated conversations often feel "one-way" and described needing to consciously prompt him to ask questions about others. Dad reported that Oliver often misses sarcasm, jokes, or implied meaning and tends to interpret language literally. Parents noted that if family members become upset or emotional, Oliver may appear confused regarding what response is expected. Emotional reciprocity appears inconsistent and often dependent on explicit prompting.

Teacher reports describe ongoing social vulnerability within the school environment. Oliver reportedly wants friendships but struggles to maintain them due to rigidity, inflexibility, and difficulty reading social situations. He often attempts to control games and becomes distressed if peers do not follow his preferred rules or sequence. Teachers described him as gravitating toward adults during break times or wandering around the playground alone. Mum stated he is frequently excluded from peer groups but does not fully recognise when this is occurring.

Parents reported longstanding rigidity around routines, expectations, and transitions. Oliver reportedly requires repeated reassurance regarding upcoming plans and becomes distressed by unpredictability. Mum stated even small changes such as taking a different road home, moving furniture, using a different plate, or changing weekend plans can trigger significant dysregulation. Parents described prolonged questioning around routines and repetitive reassurance seeking throughout the day.

Transitions away from preferred activities are extremely difficult. Parents described regular meltdowns involving yelling, crying, pacing, slamming doors, and occasionally throwing objects when electronics are turned off unexpectedly. Mum stated that after school he often appears emotionally exhausted and unable to tolerate additional demands. Teacher reports similarly note increased dysregulation later in the school day and during transitions between classroom activities.

Repetitive behaviours have reportedly been present across development. Parents observed repetitive pacing, finger movements, repeating phrases from YouTube videos, and repeatedly asking the same questions despite receiving answers. Mum also described repetitive checking behaviours and periods where Oliver became highly focused on spinning objects such as fans, washing machines, or wheels.

Restricted interests have reportedly dominated play and conversation over time. Mum stated interests become "all consuming" and difficult to interrupt. Historical interests have included Thomas the Tank Engine, vacuum cleaners, road signs, elevators, world flags, and currently transport systems. Parents report that Oliver prefers factual information and often memorises highly detailed content. Teacher reports indicate these interests frequently interfere with classroom participation due to repeated redirection of unrelated discussion topics.

Sensory sensitivities appear significant and pervasive across settings. Parents described marked auditory sensitivity including covering ears during assemblies, public toilets, hand dryers, blenders, and vacuum cleaners. Haircuts reportedly require extensive preparation due to distress associated with clippers and touch sensations. Mum reported ongoing difficulties with clothing textures, seams, socks, and tags, with Oliver often refusing certain outfits entirely. Food repertoire is extremely restricted with strong aversion to mixed textures and unfamiliar foods. Parents also described sensory seeking behaviours including crashing into furniture, excessive jumping, seeking deep pressure, and chewing objects when dysregulated.

Adaptive functioning concerns remain significant. Parents reported Oliver requires ongoing supervision and prompting for hygiene, dressing, school preparation, and emotional regulation. Mum stated that without direct prompting tasks are often not completed. Organisational skills are poor and he reportedly becomes overwhelmed completing multi-step instructions independently. School accommodations currently include educational assistant support, regulation breaks, modified group expectations, and classroom adjustments for sensory regulation.

Safety concerns were also raised. Parents reported previous incidents of wandering away in busy public settings including shopping centres and difficulty recognising environmental danger when emotionally dysregulated or highly focused on interests. Road awareness is reportedly inconsistent and parents do not currently feel safe allowing independent community access.

Across developmental history, behavioural observations, parent interview, and school collateral information, there is evidence of longstanding differences in social communication, reciprocal interaction, flexibility, sensory processing, restricted interests, and adaptive functioning present across home, school, and community settings since the early developmental period. Functional impact appears clinically significant across social, educational, emotional, and daily living domains.`;
