import { StyleSheet } from "@react-pdf/renderer";
import { BRAND, BRAND_LIGHT, INK, LEGEND_BG, MUTED, RULE, SUBTLE } from "./tokens";

export const styles = StyleSheet.create({
  page: {
    paddingTop: 50,
    paddingBottom: 50,
    paddingLeft: 60,
    paddingRight: 60,
    fontFamily: "Inter",
    fontSize: 10,
    lineHeight: 1.5,
    color: INK,
  },
  body: {
    fontSize: 10,
    fontWeight: 400,
    lineHeight: 1.5,
    color: INK,
    textAlign: "left",
  },
  boilerplate: {
    fontSize: 10,
    fontWeight: 400,
    lineHeight: 1.5,
    color: INK,
    textAlign: "left",
  },
  sectionHeadingWrap: {
    marginTop: 20,
    marginBottom: 10,
    alignSelf: "flex-start",
    borderBottomWidth: 2,
    borderBottomColor: BRAND,
    paddingBottom: 4,
  },
  sectionHeading: {
    fontSize: 13,
    fontWeight: 600,
    color: INK,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  subsectionHeading: {
    fontSize: 11,
    fontWeight: 600,
    color: BRAND,
    marginTop: 14,
    marginBottom: 6,
  },
  documentTitle: {
    fontSize: 11,
    fontWeight: 600,
    color: INK,
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },
  documentSubtitle: {
    fontSize: 9,
    fontWeight: 400,
    fontStyle: "italic",
    color: MUTED,
    marginTop: 2,
  },
  mastheadStrip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingBottom: 12,
  },
  logo: {
    width: 130,
    height: 42,
    objectFit: "contain",
  },
  confidentialMark: {
    fontSize: 8,
    fontWeight: 600,
    color: MUTED,
    textTransform: "uppercase",
    letterSpacing: 2,
    textAlign: "right",
  },
  titleBlock: {
    marginBottom: 16,
  },
  horizontalRule: {
    borderBottomWidth: 1,
    borderBottomColor: RULE,
  },
  identityRow: {
    flexDirection: "row",
    gap: 24,
  },
  identityColumn: {
    flex: 1,
  },
  blockLabel: {
    fontSize: 8,
    fontWeight: 600,
    color: MUTED,
    textTransform: "uppercase",
    letterSpacing: 2,
    marginBottom: 6,
  },
  fieldStack: {
    marginBottom: 8,
  },
  fieldLabel: {
    fontSize: 8,
    fontWeight: 500,
    color: MUTED,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  fieldValue: {
    fontSize: 10,
    fontWeight: 400,
    color: INK,
    lineHeight: 1.45,
  },
  metadataStrip: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    marginBottom: 18,
  },
  metadataItem: {
    minWidth: "22%",
    flexGrow: 1,
  },
  metadataLabel: {
    fontSize: 8,
    fontWeight: 500,
    color: MUTED,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 2,
  },
  metadataValue: {
    fontSize: 10,
    fontWeight: 400,
    color: INK,
  },
  criterionHeadingRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
    marginTop: 14,
    marginBottom: 6,
  },
  criterionTitle: {
    fontSize: 11,
    fontWeight: 600,
    color: BRAND,
  },
  ratingPill: {
    backgroundColor: BRAND_LIGHT,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 3,
  },
  ratingPillText: {
    fontSize: 9,
    fontWeight: 600,
    color: BRAND,
    textTransform: "uppercase",
  },
  criterionDescription: {
    fontSize: 10,
    fontWeight: 400,
    color: MUTED,
    marginBottom: 8,
    lineHeight: 1.5,
  },
  domainDescription: {
    fontSize: 10,
    fontWeight: 400,
    color: MUTED,
    marginBottom: 8,
    lineHeight: 1.5,
  },
  ratingLegend: {
    backgroundColor: LEGEND_BG,
    padding: 12,
    borderRadius: 4,
    marginTop: 8,
    marginBottom: 14,
  },
  ratingLegendRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 4,
  },
  ratingLegendNumber: {
    width: 16,
    fontSize: 9,
    fontWeight: 600,
    color: BRAND,
  },
  ratingLegendLabel: {
    flex: 1,
    fontSize: 9,
    fontWeight: 400,
    color: INK,
    lineHeight: 1.45,
  },
  footerWrap: {
    position: "absolute",
    left: 60,
    right: 60,
    bottom: 24,
  },
  footerRule: {
    borderTopWidth: 0.5,
    borderTopColor: RULE,
    marginBottom: 6,
  },
  footerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footerLeft: {
    flex: 1,
    fontSize: 8,
    fontWeight: 600,
    color: MUTED,
  },
  footerCenter: {
    flex: 1,
    fontSize: 8,
    fontWeight: 400,
    color: MUTED,
    textAlign: "center",
  },
  footerRight: {
    flex: 1,
    fontSize: 8,
    fontWeight: 400,
    color: SUBTLE,
    textAlign: "right",
  },
  signatureClosing: {
    fontSize: 10,
    fontWeight: 400,
    color: INK,
    marginTop: 32,
    marginBottom: 24,
  },
  signatureDivider: {
    borderTopWidth: 1,
    borderTopColor: RULE,
    marginTop: 24,
    marginBottom: 24,
  },
  signatureImage: {
    width: 100,
    height: 58,
    marginBottom: 8,
    objectFit: "contain",
  },
  signaturePlaceholder: {
    fontSize: 10,
    fontWeight: 400,
    color: INK,
    marginBottom: 8,
  },
  signatureName: {
    fontSize: 11,
    fontWeight: 600,
    color: INK,
  },
  signatureLine: {
    fontSize: 10,
    fontWeight: 400,
    color: MUTED,
  },
  signaturePractice: {
    fontSize: 10,
    fontWeight: 400,
    color: BRAND,
    marginTop: 4,
  },
});
