"""Canonical enumerations for the Gen 2 runtime."""

from __future__ import annotations

from enum import Enum


class StrEnum(str, Enum):
    def __str__(self) -> str:
        return self.value


class SessionMode(StrEnum):
    TEXT = "TEXT"
    VOICE = "VOICE"


class SafetyState(StrEnum):
    GREEN = "GREEN"
    AMBER = "AMBER"
    AMBER_HIGH = "AMBER_HIGH"
    RED = "RED"
    EMERGENCY = "EMERGENCY"


class SupportState(StrEnum):
    UNRESOLVED = "UNRESOLVED"
    MILD_TO_MODERATE = "MILD_TO_MODERATE"
    MODERATE = "MODERATE"
    MODERATE_HIGH = "MODERATE_HIGH"
    SEVERE_PENDING = "SEVERE_PENDING"


class TurnState(StrEnum):
    IDLE = "IDLE"
    LISTENING = "LISTENING"
    USER_SPEAKING = "USER_SPEAKING"
    ENDPOINT_PENDING = "ENDPOINT_PENDING"
    PROCESSING = "PROCESSING"
    SPEAKING = "SPEAKING"
    INTERRUPTED = "INTERRUPTED"
    SAFETY_MODE = "SAFETY_MODE"


class TurnEvent(StrEnum):
    SESSION_CONNECT = "session_connect"
    SPEECH_START = "speech_start"
    ENDPOINT_SILENCE = "endpoint_silence"
    STATE_SAFETY_PASS = "state_safety_pass"
    FIRST_TOKEN = "first_token"
    TURN_COMPLETE = "turn_complete"
    BARGE_IN = "barge_in"
    USER_SPOKE = "user_spoke"
    SAFETY_TRIGGER = "safety_trigger"
    SAFETY_RELEASE = "safety_release"
    SAFETY_HOLD = "safety_hold"


class Domain(StrEnum):
    MILD_DISTRESS = "MILD_DISTRESS"
    NEURO_EXEC_FUNCTION = "NEURO_EXEC_FUNCTION"
    WORK_STRESS = "WORK_STRESS"


class UserState(StrEnum):
    TASK_INITIATION_BLOCK = "TASK_INITIATION_BLOCK"
    WORKING_MEMORY_OVERLOAD = "WORKING_MEMORY_OVERLOAD"
    TASK_SWITCH_FRICTION = "TASK_SWITCH_FRICTION"
    ROLE_OVERLOAD = "ROLE_OVERLOAD"
    DEADLINE_PRESSURE = "DEADLINE_PRESSURE"
    INTERPERSONAL_FRICTION = "INTERPERSONAL_FRICTION"
    MILD_AFFECTIVE_LOAD = "MILD_AFFECTIVE_LOAD"
    RUMINATION = "RUMINATION"
    LOW_ENERGY = "LOW_ENERGY"


class Arousal(StrEnum):
    LOW = "LOW"
    MODERATE = "MODERATE"
    HIGH = "HIGH"


class InterventionPrimitive(StrEnum):
    MICRO_ACTION = "MICRO_ACTION"
    GROUNDING = "GROUNDING"
    REFRAME = "REFRAME"
    PACING = "PACING"
    BOUNDARY_PROMPT = "BOUNDARY_PROMPT"
    EXTERNALIZE_STEP = "EXTERNALIZE_STEP"
    SAFETY_SIGNPOST = "SAFETY_SIGNPOST"
    CRISIS_LOCK = "CRISIS_LOCK"


class InterventionObjective(StrEnum):
    REDUCE_INITIATION_THRESHOLD = "REDUCE_INITIATION_THRESHOLD"
    REDUCE_AROUSAL = "REDUCE_AROUSAL"
    RESTORE_AGENCY = "RESTORE_AGENCY"
    CONTAIN_AFFECT = "CONTAIN_AFFECT"
    HOLD_PACE = "HOLD_PACE"
    SIGNPOST_SAFETY = "SIGNPOST_SAFETY"
    HOLD_CRISIS = "HOLD_CRISIS"


class ConversationMove(StrEnum):
    DIRECTIVE_MICRO_PROMPT = "DIRECTIVE_MICRO_PROMPT"
    REFLECTIVE_ACK = "REFLECTIVE_ACK"
    PACING_PROMPT = "PACING_PROMPT"
    GROUNDING_PROMPT = "GROUNDING_PROMPT"
    SAFETY_DIRECTIVE = "SAFETY_DIRECTIVE"
    CRISIS_HOLD = "CRISIS_HOLD"


class PolicyDecision(StrEnum):
    ALLOW = "ALLOW"
    NARROW = "NARROW"
    BLOCK_GENERATIVE = "BLOCK_GENERATIVE"


class VoicePace(StrEnum):
    LOW_AROUSAL = "LOW_AROUSAL"
    NEUTRAL = "NEUTRAL"
    CALM_SLOW = "CALM_SLOW"


class ProductMode(StrEnum):
    WELLBEING = "WELLBEING"


class ClaimCeiling(StrEnum):
    NON_DIAGNOSTIC_NON_TREATMENT = "NON_DIAGNOSTIC_NON_TREATMENT"


class SafetySignal(StrEnum):
    SELF_HARM_LEXICAL_MATCH = "SELF_HARM_LEXICAL_MATCH"
    PASSIVE_IDEATION = "PASSIVE_IDEATION"
    HOPELESSNESS = "HOPELESSNESS"
    DISTRESS = "DISTRESS"
    IMMEDIATE_INTENT = "IMMEDIATE_INTENT"
    ACTIVE_THREAT = "ACTIVE_THREAT"
    SELF_REFERENCE = "SELF_REFERENCE"
    NEGATION = "NEGATION"
    POSITIVE_EVIDENCE = "POSITIVE_EVIDENCE"
    SAFETY_ORIENTED = "SAFETY_ORIENTED"
